config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post, optional: true

  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true
  has_many :comments, dependent: :destroy

  with_options presence: true do
    validates :title
    validates :body
    validates :impression
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, presence: true

  validates :password, format: {with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i}, allow_blank: true

  attachment :profile_image
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_up_path_for(resource)
    user_path(current_user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/#{comment.post.id}" 
  end

  def destroy
    @comment = Comment.find_by(params[:id])
    @comment.destroy
    redirect_to posts_path, notice: "コメントを削除しました。" 
  end

  private
  def comment_params
    params.require(:comment).permit(:content, :post_id, :user_id).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post,only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, expect: [:index]
  
  def index
    @posts = Post.includes(:user)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.valid?
      @post.save
     return redirect_to post_path(@post), notice: "アウトプットを投稿しました。"
    else 
      render :new
    end
  end

  def edit
    if @post.user != current_user
      redirect_to posts_path, alert: '不正なアクセスです。'
    end
  end

  def update
    if @post.update(post_params)
     redirect_to posts_path(@post), notice: "アウトプット情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "アウトプットを削除しました。"
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :impression, :post)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,only: [:show, :edit, :update]
  before_action :authenticate_user!, expect: [:index]

  def index
    @users = User.all
  end

  def show
    @username = current_user.username
    @posts = current_user.posts
  end

  def edit
    if @user != current_user
      redirect_to user_path,alert: '不正なアクセスです。'
    end
  end

  def update
    if @user.update(user_params)
     redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'ログアウトしました。'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [post, comment], url: post_comments_path(@post) ) do |f| %>
    <%= f.text_area :content, class: "input-mysize" %>
    <%= f.submit "送信", class: "btn btn-outline-dark comment-submit float-right" %>
<% end %>

app/views/comments/_index.html.erb
<%= comments.count %>件コメント
<h6 class="more" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">もっと見る....</h6>
<% comments.first(2).each do |comment| %>
  <% unless comment.id.nil? %>
    <li class="comment-container">
        <div class="comment-box">
            <div class="comment-avatar">
                <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40" %>
            </div>
            <div class="comment-text">
                <p><%= link_to "@#{comment.user.username}", users_path(comment.user.id) %></p>
                <div class="comment-entry">
                    <%= comment.content %>
                    <% if comment.user == current_user %>
                        <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                            <i class="fas fa-trash" style="color: black;"></i>
                        <% end %>
                    <% end %>
                </div>
                <span class="comment-date pull-right">
                      <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                </span>
            </div>
        </div>
    </li>
  <% end %>
<% end %>

    <div class="collapse" id="collapseExample">
            <% comments.offset(2).each do |comment| %>
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-avatar">
                            <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40" %>
                        </div>
                        <div class="comment-text">
                            <p><%= link_to "@#{comment.user.username}", users_path(comment.user.id) %></p>
                            <div class="comment-entry">
                                <%= comment.content %>
                                <% if comment.user == current_user %>
                                    <%= link_to post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
    </div>

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'index', { comments: @comment.post.comments }) %>")
$("textarea").val('')

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: Inpact;">hondeput</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <br>
          <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
          <br>
          <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
 <ul>
   <% model.errors.full_messages.each do |message| %>
   <li class='error-message'><%= message %></li>
   <% end %>
 </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hondeput</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>   
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: Impact;">hondeput</h1>
        <% end %>
        <div class="navbar-burger burger" data-target="navbarExampleTransparentExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <% if user_signed_in? %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "アウトプット一覧",posts_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "新規投稿",new_post_path, class: "navbar-item button is-warning is-light" %>
          </div>

          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ユーザー一覧", users_path, class: " button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
                </p>
                <p class="control">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div id="navbarExampleTransparentExample" class="navbar-menu">
          <div class="navbar-item">
            <%= link_to "アウトプット一覧",posts_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "新規投稿",new_post_path, class: "navbar-item button is-warning is-light" %>
          </div>
           <div class="navbar-item">
              <%= link_to "ユーザー一覧", users_path, class: " button is-warning is-light" %>
          </div>
          <div class="navbar-end">
            <div class="navbar-item">
              <div class="field is-grouped">
                <p class="control">
                  <%= link_to "ログイン", new_user_session_path, class: "btn-gradient-3d-white" %>
                </p>
                <p class="control">
                  <%= link_to "新規登録", new_user_registration_path, class: "btn-gradient-3d-orange" %>
                </p>
              </div>
            </div>
          </div>
        </div>
      <% end %>

    </nav>
    <%= yield %>
  </body>
</html>

app/views/posts/_error_messages.html.erb
<% if model.errors.any? %>
 <div class="error-alert">
   <ul>
     <% model.errors.full_messages.each do |message| %>
       <li class='error-message'><%= message %></li>
     <% end %>
   </ul>
 </div>
<% end %>

app/views/posts/edit.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アウトプット編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
 <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
       <%= form_for @post do |f| %>

          <div class="field">
            <%= f.label :title, "本のタイトル", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>
          
          <div class="field">
            <%= f.label :body, "アクションプラン", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :impression, "感想", class: "label" %>
            <%= f.text_area :impression, class: "textarea" %>
          </div>
        
          <%= f.submit "更新", class: "button is-success" %>

       <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/index.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アウトプット一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
     <div class="columns is-multiline">
        <% @posts.each do |post| %>
           <div class="column is-4">
             <div class="card">
              <div class="card-text">
                <%= link_to post_path(post)do %>
                  <p class="title is-4"><%= post.title %>
                <% end %>
              </div>
            </div>

            <div class="card-content">
              <div class="media">
                   <div class="card-body">
                     <%= truncate(post.body, length: 40) %>
                   </div>                     
                </div>
              </div>

              <div class="card-content">
                  <div class="media">
                    <div class="media-left">
                      <figure class="image is-48x48">
                       <%= link_to user_path(post.user.id) do %>
                         <%= attachment_image_tag post.user, :profile_image, falback: "no-image.png" %>
                       <% end %>
                      </figure>
                    </div>

                    <div class="media-content">
                      <div class="title"><%= link_to post.user.username, user_path(post.user.id) %></div>
                    </div>
               </div>

                <div class="content">
                  <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
   </div> 
</select>

app/views/posts/new.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規アウトプット作成
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @post do |f|%>
          <%= render 'layouts/error_messages', model: f.object %>
            <div class="field">
              <%= f.label :title, "本のタイトル", class: "label" %>
              <%= f.text_field :title, class: "input" %>
            </div>

            <div class="field">
              <%= f.label :body, "アクションプラン",class: "label" %>
              <%= f.text_area :body, class: "textarea" %>
            </div>

            <div class="field">
              <%= f.label :impression, "感想", class: "label" %>
              <%= f.text_area :impression, class: "textarea" %>
            </div>

            <%= f.submit "投稿", class: "button is-success" %>
         <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/show.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        アウトプット詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
   <div class="container">
      <div class="columns is-centered">
        <div class="column is-7">
           <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <p class="title is-4"><%= @post.title %></p>
                  </div>
               </div>
               <div class="content">
                  <table class="table is-narrow">
                    <tr>
                      <th>アクションプラン</th>
                    </tr>
                    <tr>
                      <td><%= simple_format @post.body %></td>
                    </tr>
                  </table>

                  <table class="table is-narrow-2">
                    <tr>
                      <th>感想</th>
                    </tr>
                    <tr>
                      <td><%= simple_format @post.impression %></td>
                    </tr>
                  </table>
                  <% if @post.user.id == current_user.id %>
                    <%= link_to "編集", edit_post_path(@post), class: "button is-success" %>
                  <% end %>
                </div>
             </div>
          </div>
      </div>

      <div class="column is-4">
        <article class="panel is-link">
          <p class="panel-heading">
            <%= @post.user.username %>
          </p>
          <div class="panel-block">
            <p class="control">
              <%= @post.user.profile %>
            </p>
          </div>
          <%= link_to user_path(@post.user), class: "panel-block" do %>
            <span class="panel-icon">
              <i class="fas fa-user" aria-hidden="true"></i>
            </span>
            <%= @post.user.username %> さんのページへ
          <% end %>
        </article>
      </div>
  </div>
</section>

<div class="contents row">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <% if user_signed_in? %>
          <%= form_with(model: [@post, @comment], local: true) do |form| %>
            <div class="field">
              <%= form.text_area :content, class: "form-control",class: "textarea" ,rows: 3 %>
                <%= button_tag type: "submit", class: "btn btn-success float-right mt-1" do %>
                  <i class="far fa-comments"></i> コメントする
                <% end %>
              <% end %>
            </div>
        <% else %>
          <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
        <% end %>
        <div class="comments">
          <h4>＜コメント一覧＞</h4>
            <% @comments.each do |comment| %>
            
              <% unless comment.id.nil? %>
                <li class="comment-container">
                    <div class="comment-box">
                        <div class="comment-avatar">
                            <%= attachment_image_tag comment.user, :profile_image, fallback: "no_image.jpg", class:"comment-image", size: "40x40" %>
                        </div>
                        <div class="comment-text">
                            <p><%= link_to "@#{comment.user.username}", users_path(comment.user.id) %></p>
                            <div class="comment-entry">
                                <%= comment.content %>
                                <% if comment.user == current_user %>
                                    <%= link_to post_comment_path(comment.post.id, comment.id), method: :delete, class: "comment_destroy" do %>
                                        <i class="fas fa-trash" style="color: black;"></i>
                                    <% end %>
                                <% end %>
                            </div>
                            <span class="comment-date pull-right">
                                  <%= comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
                            </span>
                        </div>
                    </div>
                </li>
              <% end %>
            <% end %>
        </div>
    </div>
   </p>
 </div>
</div>

app/views/users/edit.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
          <div class="field">
            <%= f.label :username, "ユーザー名", class: "label" %>
            <%= f.text_field :username, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :email, "メールアドレス", class: "label" %>
            <%= f.text_field :email, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :profile, "プロフィール", class: "label" %>
            <%= f.text_field :profile, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :profile_image, "プロフィール画像", class: "label" %>
            <%= f.attachment_field :profile_image, class: "input" %>
          </div>

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>

      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-content">
              <div class="card-image">
                <figure class="image">
                  <%= link_to user_path(user) do %>
                    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, fallback: "no-image.png" %>
                  <% end %>
                </figure>
              </div>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <div class="title"><%=link_to user.username, user_path(user) %></div>
                </div>
              </div>
              <div class="content">投稿数：<%= user.posts.count %></div> 
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section class="hero is-dark">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        マイページ
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png", class: "profile_image is-rounded" %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.username %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
            <table class="table is-fullwidth">
              <tr>
                <td>
                  <%= @user.profile %>
                </td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="contents row">
  <p class="title is-4"><%= @user.username %>さんの投稿一覧</p>
  <section class="section">
    <div class="container">
      <div class="columns is-multiline">
      　 <% @user.posts.each do |post| %>
          <div class="column is-7">
            <div class="card">
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                     <p class="title is-5"><%= post.title %></p>
                  </div>
                </div>
                <div class="content">
                  <table class="table is-narrow">
                    <span class="name"><%= simple_format post.body %></span> 
                  </table>
                </div>
                <div class="card-content">
                  <div class="media">
                    <div class="media-content">
                       <%= link_to post_path(post), class: "panel-block" do %>
                          <span class="panel-icon">
                            <i class="fas fa-book" aria-hidden="true"></i>
                          </span>
                          このアウトプットを見る
                        <% end %>
                        <% if @user.id == current_user.id %>
                          <%= link_to edit_post_path(post), class: "panel-block" do %>
                            <span class="panel-icon">
                              <i class="fas fa-edit"></i>
                            </span>
                              このアウトプットを編集する
                          <% end %>
                        
                          <%= link_to post_path(post.id), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                            <span class="panel-icon">
                              <i class="fas fa-trash"></i>
                            </span>
                            このアウトプットを削除する
                          <% end %>
                        <% end %>
                     </div>
                    </div>
                    <div class="content">
                      <time><%= post.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <div>
  </section>
</div>